server:
  port: 8803
spring:
  application:
    name: user-service
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    encoding: utf-8
    content-type: text/xml
    mode: HTM5
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/resume?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.wankang.entity
  configuration:
    map-underscore-to-camel-case: true

  #pagehelper
  pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

  logging:
    level:
      com.along.dao: debug
