#spring.application.name=user-service
#eureka.client.serviceUrl.defaultZone=http://springcloud:springcloud@localhost:8761/eureka/
#spring.cloud.config.discovery.serviceId=config-server
#spring.cloud.config.discovery.enabled=true
#spring.cloud.config.profile=default
#spring.cloud.config.label=master
spring:
  application:
    name: user-service
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    encoding: utf-8
    content-type: text/xml
    mode: HTM5
    cache: false
  datasource:
    url: jdbc:mysql://115.28.130.238:3306/resume?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/
server:
  port: 8803
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.wankang.entity
  configuration:
    map-underscore-to-camel-case: true

  #pagehelper
  pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

  logging:
    level:
      com.along.dao: debug
